name: test_rubydog_riverpod
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_hooks:
  flutter_riverpod: ^2.3.4
  riverpod_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:
  riverpod_generator: ^2.1.6

flutter:

  uses-material-design: true
